#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation = true
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.H2Dialect


spring.jpa.database-platform = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
# for production environment, this variable should be validate
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto = create-drop

spring.datasource.url = jdbc:postgresql://pgserver:5432/soccernowdb
spring.datasource.username = user
spring.datasource.password = password

spring.jpa.show-sql=true


logging.level.org.springframework=INFO
logging.level.com.mkyong=INFO
logging.level.com.zaxxer=DEBUG
logging.level.root=ERROR


spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5

logging.pattern.console=%-5level %logger{36} - %msg%n


spring.jpa.properties.hibernate.query.in_clause_parameter_padding=true
spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.batch_versioned_data=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL95Dialect